# Generated by Django 3.1.3 on 2022-06-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20220618_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
